config/routes.rb
Rails.application.routes.draw do
  
  get 'congrats_new/congrats'

  resources :aol_fours

  resources :aol_threes

  resources :aol_twos

  resources :aol_ones

  resources :high_scores

  resources :questions_aol_1s

  resources :course_informations

  resources :p_informations

  resources :p_infos

  resources :professor_schedules

  resources :professors
  
  resources :congrats

  devise_for :users
  resources :listings

  get 'pages/about'

  get 'pages/contact'
  
  root "pages#about"

  
  
end

app/models/aol_four.rb
class AolFour < ActiveRecord::Base
end

app/models/aol_one.rb
class AolOne < ActiveRecord::Base
end

app/models/aol_three.rb
class AolThree < ActiveRecord::Base
end

app/models/aol_two.rb
class AolTwo < ActiveRecord::Base
end

app/models/course_information.rb
class CourseInformation < ActiveRecord::Base
  
   belongs_to :user
end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
end

app/models/p_information.rb
class PInformation < ActiveRecord::Base
  belongs_to :user
end

app/models/professor.rb
class Professor < ActiveRecord::Base
  
   belongs_to :user
end

app/models/questions_aol_1.rb
class QuestionsAol1 < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :name, :first_name, :last_name, presence: true

  
  has_many :p_informations, dependent: :destroy
  has_many :course_informations, dependent: :destroy
end

app/controllers/aol_fours_controller.rb
class AolFoursController < ApplicationController
  before_action :set_aol_four, only: [:show, :edit, :update, :destroy]
   before_action :authenticate_user!
  before_action :check_user, only: [:edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]
  
  respond_to :html

  def index
    @aol_fours = AolFour.all
    respond_with(@aol_fours)
  end

  def show
    respond_with(@aol_four)
  end

  def new
    @aol_four = AolFour.new
    respond_with(@aol_four)
  end

  def edit
  end

  def create
    @aol_four = AolFour.new(aol_four_params)
    @aol_four.save
    respond_with(@aol_four)
  end

  def update
    @aol_four.update(aol_four_params)
    respond_with(@aol_four)
  end

  def destroy
    @aol_four.destroy
    respond_with(@aol_four)
  end

  private
    def set_aol_four
      @aol_four = AolFour.find(params[:id])
    end

    def aol_four_params
      params.require(:aol_four).permit(:q_nineteen, :q_twenty, :q_twentyone, :q_twentytwo)
    end
end

app/helpers/aol_fours_helper.rb
module AolFoursHelper
end

app/helpers/aol_ones_helper.rb
module AolOnesHelper
end

app/helpers/aol_threes_helper.rb
module AolThreesHelper
end

app/helpers/aol_twos_helper.rb
module AolTwosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/congrats_helper.rb
module CongratsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/p_infos_helper.rb
module PInfosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/aol_fours/_form.html.erb
<%= form_for(@aol_four) do |f| %>
  <% if @aol_four.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aol_four.errors.count, "error") %> prohibited this aol_four from being saved:</h2>

      <ul>
      <% @aol_four.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<hr>
  <div class="field">
    <%= f.label :q_nineteen, "How was student engagement and attendance during course?" %><br>
    <%= f.text_field :q_nineteen %>
  </div>
<hr>
  <div class="field">
    <%= f.label :q_twenty, "Did a discrepancy occur between student's performance in the course and final exam?" %><br>
    <%= f.text_field :q_twenty %>
  </div>
<hr>
  <div class="field">
    <%= f.label :q_twentyone, "What Changes did you make throughout the semster? Effective? Ineffective?" %><br>
    <%= label_tag(:q_twentyone, "Effective") %>
    <%= f.text_field :q_twentyone %> 
    <%= label_tag(:q_twentyone, "Ineffective") %>
    <%= f.text_field :q_twentyone %> 
   
  </div>
<hr>
  <div class="field">
    <%= f.label :q_twentytwo, "What strategies do you plan to implement to improve student learning?" %><br>
    <%= f.text_field :q_twentytwo %>
  </div>
<hr>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aol_fours/edit.html.erb
<h1>Editing aol_four</h1>

<%= render 'form' %>

<%= link_to 'Show', @aol_four %> |
<%= link_to 'Back', aol_fours_path %>

app/views/aol_fours/index.html.erb
<h1>AOL Page 4 Final Page</h1>

<table>
  <thead>
    <tr>
      <th>Question nineteen</th>
      <th>Question twenty</th>
      <th>Question twentyone</th>
      <th>Question twentytwo</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @aol_fours.each do |aol_four| %>
      <tr>
        <td><%= aol_four.q_nineteen %></td>
        <td><%= aol_four.q_twenty %></td>
        <td><%= aol_four.q_twentyone %></td>
        <td><%= aol_four.q_twentytwo %></td>
        <td><%= link_to 'Show', aol_four %></td>
        <td><%= link_to 'Edit', edit_aol_four_path(aol_four) %></td>
        <td><%= link_to 'Destroy', aol_four, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aol four', new_aol_four_path %>

app/views/aol_fours/new.html.erb
<h1>AOL Page 4</h1>

<%= render 'form' %>

<%= link_to 'Back', aol_fours_path %>

app/views/aol_fours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>How was student engagement and attendance during course?</strong>
  <%= @aol_four.q_nineteen %>
</p>

<p>
  <strong>Did a discrepancy occur between student's performance in the course and final exam?</strong>
  <%= @aol_four.q_twenty %>
</p>

<p>
  <strong>What Changes did you make throughout the semster? Effective? Ineffective?</strong>
  <%= @aol_four.q_twentyone %>
</p>

<p>
  <strong>What strategies do you plan to implement to improve student learning?</strong>
  <%= @aol_four.q_twentytwo %>
</p>

<%= link_to 'Edit', edit_aol_four_path(@aol_four) %> |
<%= link_to 'Complete AOL Form Submission', congrats_new_congrats_path %>