config/routes.rb
Rails.application.routes.draw do
  
  get 'congrats_new/congrats'

  resources :aol_fours

  resources :aol_threes

  resources :aol_twos

  resources :aol_ones

  resources :high_scores

  resources :questions_aol_1s

  resources :course_informations

  resources :p_informations

  resources :p_infos

  resources :professor_schedules

  resources :professors
  
  resources :congrats

  devise_for :users
  resources :listings

  get 'pages/about'

  get 'pages/contact'
  
  root "pages#about"

  
  
end

app/models/aol_four.rb
class AolFour < ActiveRecord::Base
end

app/models/aol_one.rb
class AolOne < ActiveRecord::Base
end

app/models/aol_three.rb
class AolThree < ActiveRecord::Base
end

app/models/aol_two.rb
class AolTwo < ActiveRecord::Base
end

app/models/course_information.rb
class CourseInformation < ActiveRecord::Base
  
   belongs_to :user
end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
end

app/models/p_information.rb
class PInformation < ActiveRecord::Base
  belongs_to :user
end

app/models/professor.rb
class Professor < ActiveRecord::Base
  
   belongs_to :user
end

app/models/questions_aol_1.rb
class QuestionsAol1 < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :name, :first_name, :last_name, presence: true

  
  has_many :p_informations, dependent: :destroy
  has_many :course_informations, dependent: :destroy
end

app/controllers/aol_threes_controller.rb
class AolThreesController < ApplicationController
  before_action :set_aol_three, only: [:show, :edit, :update, :destroy]
   before_action :authenticate_user!
  before_action :check_user, only: [:edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]
  
  respond_to :html

  def index
    @aol_threes = AolThree.all
    respond_with(@aol_threes)
  end

  def show
    respond_with(@aol_three)
  end

  def new
    @aol_three = AolThree.new
    respond_with(@aol_three)
  end

  def edit
  end

  def create
    @aol_three = AolThree.new(aol_three_params)
    @aol_three.save
    respond_with(@aol_three)
  end

  def update
    @aol_three.update(aol_three_params)
    respond_with(@aol_three)
  end

  def destroy
    @aol_three.destroy
    respond_with(@aol_three)
  end

  private
    def set_aol_three
      @aol_three = AolThree.find(params[:id])
    end

    def aol_three_params
      params.require(:aol_three).permit(:q_thirthteen, :q_fourthteen, :q_fithteen, :q_sixthteen, :q_seventeen, :q_eightteen)
    end
end

app/helpers/aol_fours_helper.rb
module AolFoursHelper
end

app/helpers/aol_ones_helper.rb
module AolOnesHelper
end

app/helpers/aol_threes_helper.rb
module AolThreesHelper
end

app/helpers/aol_twos_helper.rb
module AolTwosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/congrats_helper.rb
module CongratsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/p_infos_helper.rb
module PInfosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/aol_threes/_form.html.erb
<%= form_for(@aol_three) do |f| %>
  <% if @aol_three.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aol_three.errors.count, "error") %> prohibited this aol_three from being saved:</h2>

      <ul>
      <% @aol_three.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<hr>
  <div class="field">
    <%= f.label :q_thirthteen, "What were the course learning objectives and how did the final emcompass that?" %><br>
    <%= f.text_field :q_thirthteen %> 
    
  </div>
<hr>
  <div class="field">
    <%= f.label :q_fourthteen, "Indicate the number of students that scored in the following ranges" %><br>
    <%= label_tag(:q_fourthteen, "100%-90%") %>
    <%= f.text_field :q_fourthteen %> 
    <%= label_tag(:fourthteen, "90%-80%") %>
    <%= f.text_field :q_fourthteen %> 
    <%= label_tag(:fourthteen, "80%-70%") %>
    <%= f.text_field :q_fourthteen %>
    <%= label_tag(:fourthteen, "70%-60%") %>
    <%= f.text_field :q_fourthteen %> 
    <%= label_tag(:fourthteen, "60% Below") %>
    <%= f.text_field :q_fourthteen %> 

  </div>
<hr>
  <div class="field">
    <%= f.label :q_fithteen, "Is the faculty satisfied with a final exam as a means to assess students? Why or why not?"  %><br>
    <%= f.text_field :q_fithteen %>
  </div>
<hr>
  <div class="field">
    <%= f.label :q_sixthteen, "On the final exam in what areas do students excel?" %><br>
    <%= f.text_field :q_sixthteen %>
  </div>
<hr>
  <div class="field">
    <%= f.label :q_seventeen, "What will the faculty do to improve those areas where students perform poorly" %><br>
    <%= f.text_field :q_seventeen %>
  </div>
<hr>
  <div class="field">
    <%= f.label :q_eightteen, "Indicate the number of students who earn the following grade" %><br>
     <%= label_tag(:q_eightteen, "A") %>
    <%= f.text_field :q_eightteen %> 
    <%= label_tag(:q_eightteen, "B") %>
    <%= f.text_field :q_eightteen %> 
    <%= label_tag(:q_eightteen, "C") %>
    <%= f.text_field :q_eightteen %>
    <%= label_tag(:q_eightteen, "D") %>
    <%= f.text_field :q_eightteen %> 
    <%= label_tag(:q_eightteen, "F") %>
    <%= f.text_field :q_eightteen %>
  </div>
<hr>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/aol_threes/edit.html.erb
<h1>AOL Page 3</h1>

<%= render 'form' %>

<%= link_to 'Show', @aol_three %> |
<%= link_to 'Back', aol_threes_path %>

app/views/aol_threes/index.html.erb
<h1>AOL Page 3</h1>

<table>
  <thead>
    <tr>
      <th>Question thirthteen</th>
      <th>Question fourthteen</th>
      <th>Question fithteen</th>
      <th>Question sixthteen</th>
      <th>Question seventeen</th>
      <th>Question eightteen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aol_threes.each do |aol_three| %>
      <tr>
        <td><%= aol_three.q_thirthteen %></td>
        <td><%= aol_three.q_fourthteen %></td>
        <td><%= aol_three.q_fithteen %></td>
        <td><%= aol_three.q_sixthteen %></td>
        <td><%= aol_three.q_seventeen %></td>
        <td><%= aol_three.q_eightteen %></td>
        <td><%= link_to 'Show', aol_three %></td>
        <td><%= link_to 'Edit', edit_aol_three_path(aol_three) %></td>
        <td><%= link_to 'Destroy', aol_three, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aol three', new_aol_three_path %>

app/views/aol_threes/new.html.erb
<h1>AOL Page 3</h1>

<%= render 'form' %>

<%= link_to 'Back', aol_threes_path %>

app/views/aol_threes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>What were the course learning objectives and how did the final emcompass that?</strong>
  <%= @aol_three.q_thirthteen %>
</p>

<p>
  <strong>Indicate the number of students that scored in the following ranges?</strong>
  <%= @aol_three.q_fourthteen %>
</p>

<p>
  <strong>Is the faculty satisfied with a final exam as a means to assess students? Why or why not?</strong>
  <%= @aol_three.q_fithteen %>
</p>

<p>
  <strong>On the final exam in what areas do students excel?</strong>
  <%= @aol_three.q_sixthteen %>
</p>

<p>
  <strong>What will the faculty do to improve those areas where students perform poorly?</strong>
  <%= @aol_three.q_seventeen %>
</p>

<p>
  <strong>Indicate the number of students who earn the following grade?</strong>
  <%= @aol_three.q_eightteen %>
</p>

<%= link_to 'Edit', edit_aol_three_path(@aol_three) %> |
<%= link_to 'Last Page', new_aol_four_path %>