config/routes.rb
Rails.application.routes.draw do
  
  get 'congrats_new/congrats'

  resources :aol_fours

  resources :aol_threes

  resources :aol_twos

  resources :aol_ones

  resources :high_scores

  resources :questions_aol_1s

  resources :course_informations

  resources :p_informations

  resources :p_infos

  resources :professor_schedules

  resources :professors
  
  resources :congrats

  devise_for :users
  resources :listings

  get 'pages/about'

  get 'pages/contact'
  
  root "pages#about"

  
  
end

app/models/aol_four.rb
class AolFour < ActiveRecord::Base
end

app/models/aol_one.rb
class AolOne < ActiveRecord::Base
end

app/models/aol_three.rb
class AolThree < ActiveRecord::Base
end

app/models/aol_two.rb
class AolTwo < ActiveRecord::Base
end

app/models/course_information.rb
class CourseInformation < ActiveRecord::Base
  
   belongs_to :user
end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
end

app/models/p_information.rb
class PInformation < ActiveRecord::Base
  belongs_to :user
end

app/models/professor.rb
class Professor < ActiveRecord::Base
  
   belongs_to :user
end

app/models/questions_aol_1.rb
class QuestionsAol1 < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :name, :first_name, :last_name, presence: true

  
  has_many :p_informations, dependent: :destroy
  has_many :course_informations, dependent: :destroy
end

app/controllers/aol_ones_controller.rb
class AolOnesController < ApplicationController
  before_action :set_aol_one, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :check_user, only: [:edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]
  

  respond_to :html

  def index
    @aol_ones = AolOne.all
    respond_with(@aol_ones)
  end

  def show
    respond_with(@aol_one)
  end

  def new
    @aol_one = AolOne.new
    respond_with(@aol_one)
  end

  def edit
  end

  def create
    @aol_one = AolOne.new(aol_one_params)
    @aol_one.save
    respond_with(@aol_one)
  end

  def update
    @aol_one.update(aol_one_params)
    respond_with(@aol_one)
  end

  def destroy
    @aol_one.destroy
    respond_with(@aol_one)
  end

  private
    def set_aol_one
      @aol_one = AolOne.find(params[:id])
    end

    def aol_one_params
      params.require(:aol_one).permit(:q_one, :q_two, :q_three, :q_four, :q_five, :q_six)
    end
end

app/helpers/aol_fours_helper.rb
module AolFoursHelper
end

app/helpers/aol_ones_helper.rb
module AolOnesHelper
end

app/helpers/aol_threes_helper.rb
module AolThreesHelper
end

app/helpers/aol_twos_helper.rb
module AolTwosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/congrats_helper.rb
module CongratsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/p_infos_helper.rb
module PInfosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/aol_ones/_form.html.erb
<%= form_for(@aol_one) do |f| %>
  <% if @aol_one.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aol_one.errors.count, "error") %> prohibited this aol_one from being saved:</h2>

      <ul>
      <% @aol_one.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<hr>
  <div class="field">
    <%= f.label :q_one, "What is the required text for this course? Is it department wide?" %><br>
    <%= f.text_field :q_one %>
  </div>
<hr>
  <div class="field">
    <%= f.label :q_two,"Did the faculty use the same syllabus? If it differed, how?" %><br>
    <%= f.text_field :q_two %>
  </div>
<hr>
  <div class="field">
    <%= f.label :q_three, "Did each faculty member complete the topics outlined in the syllabus?" %><br>
    <%= f.text_field :q_three %>
  </div>
<hr>
  <div class="field">
    <%= f.label :q_four, "Describe the format of the class? (lectures, presentations, etc)" %><br>
    <%= f.text_field :q_four %>
  </div>
<hr>
  <div class="field">
    <%= f.label :q_five, "Describe the extent to which the case method was used in your class" %><br>
    <%= f.text_field :q_five %>
  </div>
<hr>
  <div class="field">
    <%= f.label :q_six, "Explain the extent to which students had to write? Was their grade impacted by these assignments" %><br>
    <%= f.text_field :q_six %>
  </div>
<hr>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<hr>
<% end %>

app/views/aol_ones/edit.html.erb
<h1>AOL Page 1</h1>

<%= render 'form' %>

<%= link_to 'Show', @aol_one %> |
<%= link_to 'Back', aol_ones_path %>

app/views/aol_ones/index.html.erb
<h1>AOL Responses Page 1</h1>

<table>
  <thead>
    <tr>
      <th>Question 1</th>
      <th>Question 2</th>
      <th>Question 3</th>
      <th>Question 4</th>
      <th>Question 5</th>
      <th>Question 6</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aol_ones.each do |aol_one| %>
      <tr>
        <td><%= aol_one.q_one %></td>
        <td><%= aol_one.q_two %></td>
        <td><%= aol_one.q_three %></td>
        <td><%= aol_one.q_four %></td>
        <td><%= aol_one.q_five %></td>
        <td><%= aol_one.q_six %></td>
        <td><%= link_to 'Show', aol_one %></td>
        <td><%= link_to 'Edit', edit_aol_one_path(aol_one) %></td>
        <td><%= link_to 'Destroy', aol_one, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aol one', new_aol_one_path %>

app/views/aol_ones/new.html.erb
<h1>AOL Page 1</h1>

<%= render 'form' %>

<%= link_to 'Back', aol_ones_path %>

app/views/aol_ones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>"What is the required text for this course? Is it department wide?"</strong>
  <%= @aol_one.q_one %>
</p>

<p>
  <strong>"Did the faculty use the same syllabus? If it differed, how?"</strong>
  <%= @aol_one.q_two %>
</p>

<p>
  <strong>"Describe the format of the class? (lectures, presentations, etc)"</strong>
  <%= @aol_one.q_three %>
</p>

<p>
  <strong>"Describe the extent to which the case method was used in your class"</strong>
  <%= @aol_one.q_four %>
</p>

<p>
  <strong>"Explain the extent to which students had to write? Was their grade impacted by these assignments"</strong>
  <%= @aol_one.q_five %>
</p>

<p>
  <strong>"Explain the extent to which students had to write? Was their grade impacted by these assignments"</strong>
  <%= @aol_one.q_six %>
</p>

<%= link_to 'Edit', edit_aol_one_path(@aol_one) %> |
<%= link_to 'Next Page', new_aol_two_path %>