config/routes.rb
Rails.application.routes.draw do
  
  get 'congrats_new/congrats'

  resources :aol_fours

  resources :aol_threes

  resources :aol_twos

  resources :aol_ones

  resources :high_scores

  resources :questions_aol_1s

  resources :course_informations

  resources :p_informations

  resources :p_infos

  resources :professor_schedules

  resources :professors
  
  resources :congrats

  devise_for :users
  resources :listings

  get 'pages/about'

  get 'pages/contact'
  
  root "pages#about"

  
  
end

app/models/aol_four.rb
class AolFour < ActiveRecord::Base
end

app/models/aol_one.rb
class AolOne < ActiveRecord::Base
end

app/models/aol_three.rb
class AolThree < ActiveRecord::Base
end

app/models/aol_two.rb
class AolTwo < ActiveRecord::Base
end

app/models/course_information.rb
class CourseInformation < ActiveRecord::Base
  
   belongs_to :user
end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
end

app/models/p_information.rb
class PInformation < ActiveRecord::Base
  belongs_to :user
end

app/models/professor.rb
class Professor < ActiveRecord::Base
  
   belongs_to :user
end

app/models/questions_aol_1.rb
class QuestionsAol1 < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :name, :first_name, :last_name, presence: true

  
  has_many :p_informations, dependent: :destroy
  has_many :course_informations, dependent: :destroy
end

app/controllers/aol_twos_controller.rb
class AolTwosController < ApplicationController
  before_action :set_aol_two, only: [:show, :edit, :update, :destroy]
   before_action :authenticate_user!
  before_action :check_user, only: [:edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]
  
  respond_to :html

  def index
    @aol_twos = AolTwo.all
    respond_with(@aol_twos)
  end

  def show
    respond_with(@aol_two)
  end

  def new
    @aol_two = AolTwo.new
    respond_with(@aol_two)
  end

  def edit
  end

  def create
    @aol_two = AolTwo.new(aol_two_params)
    @aol_two.save
    respond_with(@aol_two)
  end

  def update
    @aol_two.update(aol_two_params)
    respond_with(@aol_two)
  end

  def destroy
    @aol_two.destroy
    respond_with(@aol_two)
  end

  private
    def set_aol_two
      @aol_two = AolTwo.find(params[:id])
    end

    def aol_two_params
      params.require(:aol_two).permit(:q_seven, :q_eight, :q_nine, :q_ten, :q_eleven, :q_twelve)
    end
end

app/helpers/aol_fours_helper.rb
module AolFoursHelper
end

app/helpers/aol_ones_helper.rb
module AolOnesHelper
end

app/helpers/aol_threes_helper.rb
module AolThreesHelper
end

app/helpers/aol_twos_helper.rb
module AolTwosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/congrats_helper.rb
module CongratsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/p_infos_helper.rb
module PInfosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/aol_twos/_form.html.erb
<%= form_for(@aol_two) do |f| %>
  <% if @aol_two.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aol_two.errors.count, "error") %> prohibited this aol_two from being saved:</h2>

      <ul>
      <% @aol_two.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<hr>
  <div class="field">
    <%= f.label :q_seven, "Describe how technology was used in the course" %><br>
    <%= f.text_field :q_seven %>
  </div>
<hr>
  <div class="field">
    <%= f.label :q_eight, "What assessments did the professor use over the course to assess knowledge (other than final)?" %><br>
    <%= f.text_field :q_eight %>
  </div>
<hr>
  <div class="field">
    <%= f.label :q_nine, "Did the faculty 'curve' or modify any grades during this semester" %><br>
    <%= f.text_field :q_nine %>
  </div>
<hr>
  <div class="field">
    <%= f.label :q_ten, "Describe the extra credit, its value, and impact on final grade" %><br>
    <%= f.text_field :q_ten %>
  </div>
<hr>
  <div class="field">
    
    <%= f.label :q_eleven, "Did the faculty adminster a comprehensive final exam to assess student knowledge" %><br>
    <%= f.text_field :q_eleven %>
  </div>
<hr>
  <div class="field">
    <%= f.label :"What percentage did the final exam hold for this course" %><br>
    <%= radio_button_tag(:"q_twelve", "40%") %>
    <%= label_tag(:q_twelve, "40%") %>
    <%= radio_button_tag(:q_twelve, "30%") %>
    <%= label_tag(:q_twelve, "30%") %>
    <%= radio_button_tag(:q_twelve, "15%") %>
    <%= label_tag(:q_twelve, "15%") %>
    <%= radio_button_tag(:q_twelve, "10%") %>
    <%= label_tag(:q_twelve, "10%") %>
    <%= radio_button_tag(:q_twelve, "other") %>
    <%= label_tag(:q_twelve, "other") %>
  </div>
<hr>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/aol_twos/edit.html.erb
<h1>AOL Page 2</h1>

<%= render 'form' %>

<%= link_to 'Show', @aol_two %> |
<%= link_to 'Back', aol_twos_path %>

app/views/aol_twos/index.html.erb
<h1>AOL Page 2</h1>

<table>
  <thead>
    <tr>
      <th>Question seven</th>
      <th>Question eight</th>
      <th>Question nine</th>
      <th>Question ten</th>
      <th>Question eleven</th>
      <th>Question twelve</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @aol_twos.each do |aol_two| %>
      <tr>
        <td><%= aol_two.q_seven %></td>
        <td><%= aol_two.q_eight %></td>
        <td><%= aol_two.q_nine %></td>
        <td><%= aol_two.q_ten %></td>
        <td><%= aol_two.q_eleven %></td>
        <td><%= aol_two.q_twelve %></td>
        <td><%= link_to 'Show', aol_two %></td>
        <td><%= link_to 'Edit', edit_aol_two_path(aol_two) %></td>
        <td><%= link_to 'Destroy', aol_two, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aol two', new_aol_two_path %>

app/views/aol_twos/new.html.erb
<h1>AOL Page 2</h1>

<%= render 'form' %>

<%= link_to 'Back', aol_twos_path %>

app/views/aol_twos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>"Describe how technology was used in the course" </strong>
  <%= @aol_two.q_seven %>
</p>

<p>
  <strong>"What assessments did the professor use over the course to assess knowledge (other than final)?"</strong>
  <%= @aol_two.q_eight %>
</p>

<p>
  <strong>"Did the faculty 'curve' or modify any grades during this semester"</strong>
  <%= @aol_two.q_nine %>
</p>

<p>
  <strong>"Describe the extra credit, its value, and impact on final grade"</strong>
  <%= @aol_two.q_ten %>
</p>

<p>
  <strong>"Did the faculty adminster a comprehensive final exam to assess student knowledge"</strong>
  <%= @aol_two.q_eleven %>
</p>

<p>
  <strong>"What percentage did the final exam hold for this course"</strong>
  <%= @aol_two.q_twelve %>
</p>

<%= link_to 'Edit', edit_aol_two_path(@aol_two) %> |
<%= link_to 'Next Page', new_aol_three_path %>